force-app/main/default/objects/Card__c/fields/Card_Set__c.field-meta.xml
<CustomField>
    <fullName>Card_Set__c</fullName>
    <label>Card Set</label>
    <referenceTo>Set__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Rarity__c.field-meta.xml
<CustomField>
    <fullName>Rarity__c</fullName>
    <label>Rarity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Common</fullName>
            </value>
            <value>
                <fullName>Rare</fullName>
            </value>
            <value>
                <fullName>Super Rare</fullName>
            </value>
            <value>
                <fullName>Ultra Rare</fullName>
            </value>
            <value>
                <fullName>Secret Rare</fullName>
            </value>
            <value>
                <fullName>Premium Gold Rare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Set__c/Set__c.object-meta.xml
<CustomObject>
    <label>Set</label>
    <nameField>
        <label>Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Filter.cls
public class Filter {  
    //filter by card type
    @AuraEnabled
    public static List<Card__c> FilterByCardType(String CardType){
        //String Type = '%' + CardType + '%';
        
        list <Card__c> cards = [
            SELECT Name
            FROM Card__c
            WHERE RecordType.Name IN (:CardType)
        ];
        System.debug(cards);
        for(Card__c card : cards){
            System.debug(card.Name);
        }
        //return JSON.serialize(cards);
        return cards;

    }
    //filter by rarity
    @AuraEnabled
    public static List<Card__c> FilterByRarity(String Rarity){
        //String RarityName = '%' + Rarity + '%';
        
        list <Card__c> cards = [
            SELECT Name, Rarity__c
            FROM Card__c
            WHERE Rarity__c LIKE :Rarity
        ];
        System.debug(cards);
        for(Card__c card : cards){
            System.debug(card.Name);
        }
        return cards;
    }
    //filter by set
    @AuraEnabled
    public static List<Card__c> FilterBySet(String SetName){
        //String Type = '%' + CardType + '%';
        
        list <Card__c> cards = [
            SELECT Name
            FROM Card__c
            WHERE Card_Set__r.Name LIKE :SetName
        ];
        System.debug(cards);
        for(Card__c card : cards){
            System.debug(card.Name);
        }
        return cards;
    }
    


}